# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HiveMind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HiveMind
	pod 'Firebase/Core', '5.7.0'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'

  target 'HiveMindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiveMindUITests' do
    # Pods for testing
  end

end
